services:
  - type: web
    name: arabic-vocalizer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    buildFilter:
      paths:
        - "main.py"
        - "requirements.txt"
    preBuildCommand: "apt-get update && apt-get install -y build-essential cmake"
    
